version: "3.3"
services:
  postgres:
    container_name: PIZZERIA
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./data:/my_data
    ports: 
      - "${DB_PORT}:5432"
