name: deploy
on: push
jobs:
  check_repo:
    runs-on: self-hosted
    steps:
      - name: check repo
        uses: actions/checkout@v4
  deploy:
    needs: [check_repo]
    runs-on: self-hosted
    steps:
      - name: build container
        run: docker compose -p pizza build
      - name: up container
        run: docker compose -p pizza up
