name: deploy
on: push
jobs:
  check_repo:
    runs-on: self-hosted
    steps:
      - name: check repo
        uses: actions/checkout@v4
  clear_prev_docker:
    runs-on: self-hosted
    steps:
      - name: stop container
        run: docker stop PIZZERIA
      - name: rm old container
        run: docker rm PIZZERIA
  setup_env:
    needs: [check_repo]
    runs-on: self-hosted
    steps:
      - name: setup port
        run: echo DB_PORT=${{ secrets.DB_PORT }} >> .env
      - name: setup user of db
        run: echo DB_USER=${{secrets.DB_USER}} >> .env
      - name: setup password of user for db
        run: echo DB_PASSWORD=${{secrets.DB_PASSWORD}} >> .env
      - name: setup db name
        run: echo DB_NAME=${{secrets.DB_NAME}} >> .env
  deploy:
    needs: [setup_env, clear_prev_docker]
    runs-on: self-hosted
    steps:
      - name: build container
        run: docker compose -p pizza build
      - name: up container
        run: docker compose -p pizza up -d
      - name: add container to autostart
        run: docker update --restart=on-failure PIZZERIA
  clear_env:
    needs: [deploy]
    runs-on: self-hosted
    steps:
      - name: clear env
        run: rm .env
