name: deploy
on: push
jobs:
  check_repo:
    runs-on: self-hosted
    steps:
      - name: check repo
        uses: actions/checkout@v4
  setup_env:
    needs: [check_repo]
    runs-on: self-hosted
    steps:
      - name: setup port
        run: echo DB_PORT=${{ secrets.DB_PORT }} >> .env
  deploy:
    needs: [setup_env]
    runs-on: self-hosted
    steps:
      - name: build container
        run: docker compose -p pizza build
      - name: up container
        run: docker compose -p pizza up -d
